### ISSUE TITLE
Build issue with GCC 4.9.2

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/monster-rpg-3#15]
Using the current master branches for all repos, it fails in the monster-rpg-3 one:
```
[ 40%] [ 40%] Building CXX object CMakeFiles/MonsterRPG3.dir/src/brains.cpp.o
Building CXX object CMakeFiles/MonsterRPG3.dir/src/ml_start.cpp.o
/home/akien/Projects/nooskewl/monster-rpg-3/monster-rpg-3/src/ml_start.cpp: In member function 'virtual void ML_start::start()':
/home/akien/Projects/nooskewl/monster-rpg-3/monster-rpg-3/src/ml_start.cpp:184:13: error: 'class Nooskewl_Engine::Map_Entity' has no member named 'set_high'
    bottle3->set_high(true);
             ^
/home/akien/Projects/nooskewl/monster-rpg-3/monster-rpg-3/src/ml_start.cpp:194:13: error: 'class Nooskewl_Engine::Map_Entity' has no member named 'set_high'
    bottle4->set_high(true);
             ^
/home/akien/Projects/nooskewl/monster-rpg-3/monster-rpg-3/src/brains.cpp: In member function 'virtual void Item_Brain::activate(Nooskewl_Engine::Map_Entity*)':
/home/akien/Projects/nooskewl/monster-rpg-3/monster-rpg-3/src/brains.cpp:341:9: error: 'class Nooskewl_Engine::Engine' has no member named 'item_mml'
     noo.item_mml->play(false);
         ^
```

**Comment by trentg** [comment]
Your Nooskewl Engine checkout isn't updated or you have stale headers somewhere.

**Comment by akien-mga** [comment]
Ah right thanks, my checkout was following my own branch instead of origin/master.
I had thought about adding ```git checkout master``` when writing the build.sh script, but then thought it could be a bother for community developers wanting to test their own branches ;)

I guess I'll add a command-line parameter to the build.sh script to tell it whether repos should track master or stay on their current branches (e.g. an opt-in ```build.sh custom```, so by default it would ensure that all repos track Nooskewl/master).
