### ISSUE TITLE
Can't run Nooskewl_Runner outside of its directory

### ISSUE THREAD

**Issue by ecj2** [Nooskewl/monster-rpg-3#17]
It fails to load libNooskewl_Engine.so if executed outside of its directory. I'm not sure how it works in SDL, but prepending the game path to resources would likely fix this issue.

**Comment by akien-mga** [comment]
That's normal with dynamic linking using an RPATH (relative path). The RPATH is always taken relatively to the runtime dir, and not to the dir of the binary. If you want to be able to run the game outside of its directory, then you need a wrapper script like:

```
#!/bin/sh
cd /path/to/mo3/dir
exec Nooskewl_Runner
```

**Comment by ecj2** [comment]
I understand. I still think Nooskewl_Runner should be able to be executed outside of its own directory and run without issue. Even if the game is under `/home/eric/mo3`, and the CWD is `/home/eric`, if I were to execute `./mo3/Nooskewl_Runner` from a CLI, it would still fail. Likewise, if I execute Nooskewl_Runner within its own directory from a file manager, it fails. So in other words, it only works if run within its own directory from CLI.

For ease of use, executing the binary from a GUI should work at least.

**Comment by akien-mga** [comment]
> I understand. I still think Nooskewl_Runner should be able to be executed outside of its own directory and run without issue. Even if the game is under /home/eric/mo3, and the CWD is /home/eric, if I were to execute ./mo3/Nooskewl_Runner from a CLI, it would still fail.

Yeah, but how would one achieve that? I've never seen a compiled binary that is able to locate a runtime library which is not in LD_LIBRARY_PATH, apart from binaries using RPATH like Nooskewl_Runner, but then the path is relative. But @trentg said he would fix this issue, so maybe he knows a way that I don't (apart from statically linking, but that kinds of defeats the purpose of building a shared engine library).

> Likewise, if I execute Nooskewl_Runner within its own directory from a file manager, it fails. So in other words, it only works if run within its own directory from CLI.

The binary runs just fine for me when double-clicked in Dolphin.

**Comment by ecj2** [comment]
> Yeah, but how would one achieve that?

I do not know. I will leave that up to Trent.

> The binary runs just fine for me when double-clicked in Dolphin.

Interesting. I'm using Pantheon File Manager, where it does not run when double-clicked nor when selecting "Run" from the context menu. It may be just be a bug in my file manager then.

**Comment by trentg** [comment]
It's possible to dynamically load the shared libraries and achieve this. I'm not sure if it's worth it, though. I've noticed some file managers (I believe it was XFCE's) don't handle this issue correctly. Many set the CWD before running the binary so that it works.

**Comment by ecj2** [comment]
> I'm not sure if it's worth it, though.

That's fine. The issue is not a big deal anyway.

**Comment by trentg** [comment]
Another possibility I've done before is to have an additional shell script... I can't remember how it works but it gets the directory itself is in, sets the LD_LIBRARY_PATH then runs the game. The only downside is it's another file but then the .so's can be placed in a sub directory.

**Comment by trentg** [comment]
I remembered the command, it's dirname. I'm creating a new package for Linux now.

**Comment by trentg** [comment]
Fixed.
