### ISSUE TITLE
Test in Wine

### ISSUE THREAD

**Issue by trentg** [Nooskewl/monster-rpg-3#18]
Make sure it works.

**Comment by ecj2** [comment]
From a _fresh_ install of Wine, I get the following from running `wine ./Nooskewl_Runner.exe`:

err:module:import_dll Library MSVCP120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\tgui3.dll") not found
err:module:import_dll Library MSVCR120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\tgui3.dll") not found
err:module:import_dll Library tgui3.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Engine.dll") not found
err:module:import_dll Library MSVCR120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\zlib.dll") not found
err:module:import_dll Library zlib.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\freetype.dll") not found
err:module:import_dll Library MSVCR120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\freetype.dll") not found
err:module:import_dll Library freetype.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\SDL2_ttf.dll") not found
err:module:import_dll Library MSVCR120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\SDL2_ttf.dll") not found
err:module:import_dll Library SDL2_ttf.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Engine.dll") not found
err:module:import_dll Library MSVCR120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\zlib.dll") not found
err:module:import_dll Library zlib.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Engine.dll") not found
err:module:import_dll Library MSVCP120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Engine.dll") not found
err:module:import_dll Library MSVCR120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Engine.dll") not found
err:module:import_dll Library Nooskewl_Engine.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Runner.exe") not found
err:module:import_dll Library MSVCP120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Runner.exe") not found
err:module:import_dll Library MSVCR120.dll (which is needed by L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Runner.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\eric\\MonsterRPG3-20150820\\Nooskewl_Runner.exe" failed, status c0000135

The above was tested on the 20150820 binary for Windows.

**Comment by trentg** [comment]
Most of those are MSVC resist, not sure why it can't find the others.

**Comment by ecj2** [comment]
It's Wine, after all. There's never a guarantee that it will work. Being able to play the game in Wine seems kind of silly anyhow, considering that the Linux binaries work just fine.

**Comment by akien-mga** [comment]
Well, it's interesting to run it into Wine to see how the Windows binary might behave on a Windows system with minimal dependencies. Here it shows that the game won't run if MSVC redist is missing, and if it's not the case already, the error should probably be caught to give a user-friendly error dialog to the user, telling them to install the needed version of MSVC redist.

**Comment by trentg** [comment]
That’s what installers are for, but the updates are too frequent for installers to be desirable, which is why the first post in the devlog has had the requirements listed from the beginning along with a link to download the redist. :)

**Comment by trentg** [comment]
The VC 2013 redist doesn't install on Wine for me. If I copy the msvcp120.dll and msvcr120.dll from a Windows system, the game sort of runs: D3D creates a Window, sets a custom mouse cursor, but the window is black; OpenGL works fine, except no sound.

**Comment by trentg** [comment]
My mistake, I do get sound, it was a more general system configuration issue.

**Comment by trentg** [comment]
Crystal Picnic also doesn't work in D3D mode in Wine, but works with OpenGL. Perhaps Wine's D3D support isn't very good (CP is Allegro, M3 is SDL, two different implementations don't work.)

**Comment by trentg** [comment]
Appears to be shaders that break Wine. Monster RPG 2 has a shaderless option (-fixed-pipeline) and it works in D3D mode in Wine.

**Comment by trentg** [comment]
Appears to be a known issue. From http://wiki.winehq.org/DirectX-Shaders:

    Some of the shader opcodes needed for shader versions 2 and higher are not accessible through ARB_vertex_program which is how we are currently implementing vertex and pixel shaders <= 1.4. To get this functionality, we either need to implement them via software (high CPU usage) or via GLSL (OpenGL Shading Language). 

So looks like this game will not run in Wine in D3D mode until they support shader model 2.

**Comment by trentg** [comment]
Reading more of that, looks like they have support for SM2 now but it's incomplete especiall:

    Most of the HLSL shader compiler is missing too.

So the other option is to pre-compile the shaders. Not sure how portable across systems that is, but for Wine support it's probably not worth it. Closing this issue now as it works as well as possible.
