### ISSUE TITLE
Snapping game window to sides of screen results in visual bug

### ISSUE THREAD

**Issue by ecj2** [Nooskewl/monster-rpg-3#9]
When snapping the game window to the left or right side of the desktop, the black bars that usually appear occasionally are filled with the previous frame prior to snapping.

![Image of visual bug](http://i60.tinypic.com/r0wfnd.jpg)

I have also recorded a [video of the bug](https://vid.me/g4CY).

**Comment by akien-mga** [comment]
I've tried locally but couldn't reproduce the bug. My platform is Mageia 5 64bit, with KDE4 desktop and Kwin window manager.
Could be a WM-specific issue, or related to a library (I'm using GLEW 1.11 for example, and not 1.10 as in the binary release).

**Comment by trentg** [comment]
Yeah, although I haven't yet tried this, the game does call  glClear every frame so it seems like it's not its fault, but I will look at it further.

**Comment by ecj2** [comment]
It may very well be an issue with my particular desktop environment. I'm running elementary OS 0.3 Freya 64 bit with Pantheon as the desktop environment (which was written from scratch in Vala). If this bug doesn't occur in the normal Debian flavors of Linux, you may disregard it.

**Comment by trentg** [comment]
Tested on Ubuntu 14.04 and I get the same bug. I'll look for a workaround at some point hopefully soon.

**Comment by ecj2** [comment]
Thank you.

**Comment by trentg** [comment]
Fixed this in git by clearing the screen before calls to glScissor. Oops, my bad.
